
export const label1 = {
  properties: {
    Accelerator: '',
    AutoSize: false,
    BackColor: '#D6D5D5',
    BackStyle: 1,
    BorderColor: '#D6D5D5',
    BorderStyle: 1,
    Caption: 'Label1',
    ControlTipText: 'helptext',
    Enabled: true,
    Font: {
      FontName: 'Arial',
      FontSize: 10,
      FontBold: false,
      FontItalic: false,
      FontUnderline: false,
      FontStrikethrough: false,
      FontStyle: 'Arial Narrow Italic'
    },
    ForeColor: '#000000',
    Height: 50,
    HelpContextID: 0,
    Left: 100,
    MouseIcon: '',
    MousePointer: 0,
    Name: 'Label1',
    ID: 'ID_Label1',
    Picture: '',
    PicturePosition: 7,
    SpecialEffect: 0,
    TabIndex: 0,
    TabStop: true,
    Tag: '',
    TextAlign: 0,
    Top: 10,
    Visible: true,
    Width: 72,
    WordWrap: true,
    GroupID: ''
  },
  controls: [],
  extraDatas: {
  },
  type: 'Label'
}

export const label2 = {
  properties: {
    Accelerator: '',
    AutoSize: false,
    BackColor: '#D6D5D5',
    BackStyle: 0,
    BorderColor: '#D6D5D5',
    BorderStyle: 1,
    Caption: 'Label2',
    ControlTipText: 'helptext',
    Enabled: true,
    Font: {
      FontName: 'Arial',
      FontSize: 10,
      FontBold: false,
      FontItalic: false,
      FontUnderline: false,
      FontStrikethrough: false,
      FontStyle: 'Arial Narrow Italic'
    },
    ForeColor: '#000000',
    Height: 100,
    HelpContextID: 0,
    Left: 220,
    MouseIcon: '',
    MousePointer: 0,
    Name: 'Label2',
    ID: 'ID_Label2',
    Picture: '',
    PicturePosition: 7,
    SpecialEffect: 0,
    TabIndex: 1,
    TabStop: true,
    Tag: '',
    TextAlign: 1,
    Top: 120,
    Visible: true,
    Width: 72,
    WordWrap: true,
    GroupID: ''
  },
  controls: [],
  extraDatas: {
  },
  type: 'Label'
}

export const label3 = {
  properties: {
    Accelerator: '',
    AutoSize: false,
    BackColor: '#D6D5D5',
    BackStyle: 1,
    BorderColor: '#D6D5D5',
    BorderStyle: 1,
    Caption: 'Label3',
    ControlTipText: 'helptext',
    Enabled: true,
    Font: {
      FontName: 'Arial',
      FontSize: 10,
      FontBold: false,
      FontItalic: false,
      FontUnderline: false,
      FontStrikethrough: false,
      FontStyle: 'Arial Narrow Italic'
    },
    ForeColor: '#000000',
    Height: 50,
    HelpContextID: 0,
    Left: 80,
    MouseIcon: '',
    MousePointer: 0,
    Name: 'Label3',
    ID: 'ID_Label3',
    Picture: '',
    PicturePosition: 7,
    SpecialEffect: 0,
    TabIndex: 2,
    TabStop: true,
    Tag: '',
    TextAlign: 0,
    Top: 200,
    Visible: true,
    Width: 72,
    WordWrap: true,
    GroupID: ''
  },
  controls: [],
  extraDatas: {
  },
  type: 'Label'
}

export const label4 = {
  properties: {
    Accelerator: '',
    AutoSize: false,
    BackColor: '#D6D5D5',
    BackStyle: 1,
    BorderColor: '#D6D5D5',
    BorderStyle: 1,
    Caption: 'Label4',
    ControlTipText: 'helptext',
    Enabled: true,
    Font: {
      FontName: 'Arial',
      FontSize: 10,
      FontBold: false,
      FontItalic: false,
      FontUnderline: false,
      FontStrikethrough: false,
      FontStyle: 'Arial Narrow Italic'
    },
    ForeColor: '#000000',
    Height: 50,
    HelpContextID: 0,
    Left: 350,
    MouseIcon: '',
    MousePointer: 0,
    Name: 'Label4',
    ID: 'ID_Label4',
    Picture: '',
    PicturePosition: 7,
    SpecialEffect: 0,
    TabIndex: 3,
    TabStop: true,
    Tag: '',
    TextAlign: 0,
    Top: 100,
    Visible: true,
    Width: 72,
    WordWrap: true,
    GroupID: ''
  },
  controls: [],
  extraDatas: {
  },
  type: 'Label'
}
